import type { Metadata } from "next";
import { MuseoModerno, Inter } from "next/font/google";
import "./globals.css";

const muMo = MuseoModerno({ subsets: ["latin"] });
const inter = Inter({ subsets: ["latin"] });


export const metadata: Metadata = {
  title: "Event Registration",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
        
      </body>
    </html>
  );
}
